
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import static java.lang.System.out;
import java.lang.reflect.Array;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author Ishadi
 */
class board extends javax.swing.JFrame {

    /**
     * Creates new form board
     */
    public board() {
       initComponents();
       
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btn00 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusableWindowState(false);
        setMinimumSize(new java.awt.Dimension(540, 565));
        setResizable(false);
        getContentPane().setLayout(null);

        btn00.setBorder(null);
        btn00.setContentAreaFilled(false);
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });
        getContentPane().add(btn00);
        btn00.setBounds(10, 20, 150, 150);

        btn01.setBorder(null);
        btn01.setContentAreaFilled(false);
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });
        getContentPane().add(btn01);
        btn01.setBounds(200, 20, 140, 150);

        btn02.setBorder(null);
        btn02.setContentAreaFilled(false);
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });
        getContentPane().add(btn02);
        btn02.setBounds(370, 20, 140, 150);

        btn10.setBorder(null);
        btn10.setContentAreaFilled(false);
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        getContentPane().add(btn10);
        btn10.setBounds(21, 196, 140, 150);

        btn11.setBorder(null);
        btn11.setContentAreaFilled(false);
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        getContentPane().add(btn11);
        btn11.setBounds(191, 196, 150, 150);

        btn12.setBorder(null);
        btn12.setContentAreaFilled(false);
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        getContentPane().add(btn12);
        btn12.setBounds(370, 200, 150, 140);

        btn20.setBorder(null);
        btn20.setContentAreaFilled(false);
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });
        getContentPane().add(btn20);
        btn20.setBounds(20, 370, 150, 150);

        btn21.setBorder(null);
        btn21.setContentAreaFilled(false);
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });
        getContentPane().add(btn21);
        btn21.setBounds(191, 366, 150, 150);

        btn22.setBorder(null);
        btn22.setContentAreaFilled(false);
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });
        getContentPane().add(btn22);
        btn22.setBounds(371, 366, 140, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Board1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 560, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
      checker.mark(1,btn01,Boolean.TRUE);
    }//GEN-LAST:event_btn01ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
       checker.mark(2,btn02,Boolean.TRUE);
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        checker.mark(3,btn10,Boolean.TRUE);
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
       checker.mark(4,btn11,Boolean.TRUE);
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
      checker.mark(5,btn12,Boolean.TRUE);
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
       checker.mark(6,btn20,Boolean.TRUE);
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        checker.mark(7,btn21,Boolean.TRUE);
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        checker.mark(8,btn22,Boolean.TRUE);
    }//GEN-LAST:event_btn22ActionPerformed

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
      checker.mark(0,btn00,Boolean.TRUE);
      
    }//GEN-LAST:event_btn00ActionPerformed

    public static void main(String args[]) {
      
      
       board TicTakToeboard=new board();
      // TicTakToeboard.launch();
       TicTakToeboard.setLocationRelativeTo(null);
       TicTakToeboard.setVisible(true);
       
       
    }
    
      void launch(Boolean ComMode ){  
       
       checker=new Checker();
       
       checker.launch(ComMode,this);
        if(ComMode==Boolean.TRUE)
        checker.mark(6,btn20,Boolean.FALSE);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
Checker checker;
boolean temp;

    void getnames(String player1name, String player2name)
    {
        checker.setnames(player1name,player2name);
    }
   void mark(int box)
   {
        switch(box){
            case 0:checker.mark(box, btn00,Boolean.FALSE);break;
            case 1:checker.mark(box, btn01,Boolean.FALSE);break;
            case 2:checker.mark(box, btn02,Boolean.FALSE);break;    
            case 3:checker.mark(box, btn10,Boolean.FALSE);break;    
            case 4:checker.mark(box, btn11,Boolean.FALSE);break;
            case 5:checker.mark(box, btn12,Boolean.FALSE);break;
            case 6:checker.mark(box, btn20,Boolean.FALSE);break;    
            case 7:checker.mark(box, btn21,Boolean.FALSE);break;
            case 8:checker.mark(box, btn22,Boolean.FALSE);break;    
                
        }
   }
    
    
    
    
    }
    
           
           
          
         




