
import static java.lang.System.out;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ishadi
 */
public class ScoreSheet_1 extends javax.swing.JFrame {

    /**
     * Creates new form ScoreSheet_1
     */
    public ScoreSheet_1() throws SQLException {
        initComponents();
        this.launch();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        sc2 = new javax.swing.JTextField();
        sc1 = new javax.swing.JTextField();
        nm1 = new javax.swing.JTextField();
        nm2 = new javax.swing.JTextField();
        sc3 = new javax.swing.JTextField();
        nm3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setEnabled(false);
        setMaximumSize(new java.awt.Dimension(521, 390));
        setMinimumSize(new java.awt.Dimension(521, 390));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/top3.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 450, 200);

        sc2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, new java.awt.Color(153, 153, 0)));
        sc2.setOpaque(false);
        getContentPane().add(sc2);
        sc2.setBounds(200, 250, 50, 40);

        sc1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, new java.awt.Color(153, 153, 0)));
        sc1.setOpaque(false);
        getContentPane().add(sc1);
        sc1.setBounds(200, 190, 60, 40);

        nm1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, new java.awt.Color(153, 153, 0)));
        nm1.setOpaque(false);
        getContentPane().add(nm1);
        nm1.setBounds(50, 190, 130, 40);

        nm2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, new java.awt.Color(153, 153, 0)));
        nm2.setOpaque(false);
        getContentPane().add(nm2);
        nm2.setBounds(50, 240, 130, 50);

        sc3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, new java.awt.Color(153, 153, 0)));
        sc3.setOpaque(false);
        getContentPane().add(sc3);
        sc3.setBounds(200, 300, 50, 50);

        nm3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, new java.awt.Color(153, 153, 0)));
        nm3.setOpaque(false);
        getContentPane().add(nm3);
        nm3.setBounds(50, 300, 130, 50);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 300, 200, 50);

        jLabel1.setBackground(new java.awt.Color(255, 102, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wt.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 530, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        front f=new front();
        f.setVisible(true);
        this.setVisible(false);
        f.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreSheet_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreSheet_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreSheet_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreSheet_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ScoreSheet_1().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ScoreSheet_1.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
        
    }
    void launch() throws SQLException
    {/*
        DataBaseConnector db=new DataBaseConnector();
        db.connect();
        String[] results=new String[3];
        db.getAll();
        for(int i=0;db.rs.next();i++)
                {
                    results[i]=db.rs.getString("name");
                    //out.println(records[i]);
                }
        //out.println(results);
        out.println(results[2]);
        
            if(results[0]!=null)
            {
                nm1.setText(results[0]);
                sc1.setText(Integer.toString(db.getScore(results[0])));
            }
             if(results[1]!=null)
            {
                nm2.setText(results[1]);
                sc2.setText(Integer.toString(db.getScore(results[1])));
            }
             if(results[2]!=null)
            {
                nm3.setText(results[2]);
                sc3.setText(Integer.toString(db.getScore(results[2])));
            }
        db.disconnect();     
      */  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nm1;
    private javax.swing.JTextField nm2;
    private javax.swing.JTextField nm3;
    private javax.swing.JTextField sc1;
    private javax.swing.JTextField sc2;
    private javax.swing.JTextField sc3;
    // End of variables declaration//GEN-END:variables
}
