
import static java.lang.System.out;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ishadi
 */
public class scoreSheet extends javax.swing.JFrame {

    /**
     * Creates new form scoreSheet
     */
    public scoreSheet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sc3 = new javax.swing.JTextField();
        nm3 = new javax.swing.JTextField();
        sc2 = new javax.swing.JTextField();
        nm2 = new javax.swing.JTextField();
        sc1 = new javax.swing.JTextField();
        nm1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setFocusableWindowState(false);
        setMaximumSize(new java.awt.Dimension(622, 319));
        setMinimumSize(new java.awt.Dimension(622, 319));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/top3.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 10, 360, 200);

        sc3.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        sc3.setForeground(new java.awt.Color(0, 255, 0));
        sc3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        sc3.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        sc3.setOpaque(false);
        sc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sc3ActionPerformed(evt);
            }
        });
        getContentPane().add(sc3);
        sc3.setBounds(210, 210, 70, 40);

        nm3.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        nm3.setForeground(new java.awt.Color(0, 255, 0));
        nm3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        nm3.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        nm3.setOpaque(false);
        getContentPane().add(nm3);
        nm3.setBounds(10, 200, 190, 50);

        sc2.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        sc2.setForeground(new java.awt.Color(255, 0, 0));
        sc2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        sc2.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        sc2.setOpaque(false);
        sc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sc2ActionPerformed(evt);
            }
        });
        getContentPane().add(sc2);
        sc2.setBounds(210, 130, 70, 40);

        nm2.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        nm2.setForeground(new java.awt.Color(255, 0, 0));
        nm2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        nm2.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        nm2.setOpaque(false);
        getContentPane().add(nm2);
        nm2.setBounds(10, 120, 190, 50);

        sc1.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        sc1.setForeground(new java.awt.Color(0, 0, 255));
        sc1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        sc1.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        sc1.setOpaque(false);
        getContentPane().add(sc1);
        sc1.setBounds(210, 50, 70, 40);

        nm1.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        nm1.setForeground(new java.awt.Color(0, 0, 255));
        nm1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        nm1.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        nm1.setOpaque(false);
        getContentPane().add(nm1);
        nm1.setBounds(10, 40, 190, 50);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("RETURN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 230, 150, 60);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wt.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 620, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sc2ActionPerformed

    private void sc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sc3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // front f=new front();
        //f.setVisible(true);
        //f.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scoreSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scoreSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scoreSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scoreSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                scoreSheet p=new scoreSheet();
                p.init();
                        p.setVisible(true);
                        
            }
        });
    }
    void init()
    {
        try {
            DataBaseConnector db=new DataBaseConnector();
            db.connect();
            //String sql="select * from gamer";
            ResultSet rs;
            rs=db.getAll();
            int i=0;
            if(rs.next())
            {
                nm1.setText(rs.getString("name"));
                
                sc1.setText(String.valueOf(db.getScore(rs.getString("name"))));
                
               if(rs.next())
               {
                   nm2.setText(rs.getString("name"));
                   sc2.setText(String.valueOf(db.getScore(rs.getString("name"))));
                   
                    if(rs.next())
                   {
                       nm3.setText(rs.getString("name"));
                       sc3.setText(String.valueOf(db.getScore(rs.getString("name"))));
                       

                   }
               }
               
                
            }
            
            
            db.disconnect();
        } catch (SQLException ex) {
            Logger.getLogger(scoreSheet.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nm1;
    private javax.swing.JTextField nm2;
    private javax.swing.JTextField nm3;
    private javax.swing.JTextField sc1;
    private javax.swing.JTextField sc2;
    private javax.swing.JTextField sc3;
    // End of variables declaration//GEN-END:variables
}
